### ISSUE TITLE
usage with composer based projects or similar

### ISSUE THREAD

**Issue by selul** [10up/action-wordpress-plugin-asset-update#12]
I've come across this particular workflow and I'm not sure if this is the intended behaviour or there is any workaround around this. 

Let's say have a WordPress plugin which uses some 3rd party libraries and manage them with Composer and we have the following workflow to update readme/assets with wp.org

```
name: Sync assets with wordpress.org


on:
  push:
    branches:
      - master
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Push assets to wporg
    steps:
        - uses: actions/checkout@master
        - name: WordPress.org plugin asset/readme update
          uses: 10up/action-wordpress-plugin-asset-update@master
          env:
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

```

Right now this workflow is failing due to the fact that the vendor files are missing triggering this error: ` Other files have been modified; changes not deployed` from the action. 
here you have the log [details](https://github.com/Codeinwp/blocks-css/commit/206b9c5b658b908f392a6c42f7f4c5d56721ecc9/checks?check_suite_id=387801522)

A possible fix that I was thinking about is to install the composer deps before running the action, but in this case, SVN will see the composer autoloaders as modified and again failing the deployment of the assets. 
 
This is just a basic example and not an uncommon practice for a WordPress plugin to use composer to manage 3rd party libraries. 
 
Any idea if there is any solution to this?
