### ISSUE TITLE
Error on deployment:  .github:1  Docker run failed with exit code 23

### ISSUE THREAD

**Issue by sebastienserre** [10up/action-wordpress-plugin-asset-update#16]
Hello,
I'm trying to use this actions with your others to deploy on wp.org repo but with this action I Got an error ` .github:1 Docker run failed with exit code 23` and deployment failed...

I've got in my `/github/workflows` 2 files, 1 with 

```
name: Deploy to OpenAgenda to WordPress.org
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }} 
```

and one with

``` 
name: Deploy to OpenAgenda to WordPress.org Readme
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    name: New Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
 ```

Do you know what I'm doing wrong?
